name: '🎫 Automatic check for tickets'

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  test:
    name: Main Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Automatic check
        uses: ./actions/runCheck
